# Generated by Django 3.2.5 on 2021-07-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_selectedimage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedimage',
            name='editImage',
            field=models.ImageField(blank=True, null=True, upload_to='edit'),
        ),
    ]
